apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-site-ui
spec:
  selector:
    matchLabels:
      app: tf-site-ui
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tf-site-ui
    spec:
      containers:
        - name: tf-site-ui
          image: gcr.io/pineappleworkshop/tf-site-ui:0.0.8
          env:
            - name: ENV
              value: "dev"
