apiVersion: v1
kind: Service
metadata:
  labels:
    app: tf-site-ui
  name: tf-site-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: tf-site-ui
